---
- hosts: all
  become: yes
  pre_tasks:
    - name: switch to rw mode
      ansible.builtin.command: rw

  tasks:
    - name: Upgrade system
      community.general.pacman:
        update_cache: true
        upgrade: true
    # - name: Check if reboot is needed
    #   ansible.builtin.stat:
    #     path: /var/run/reboot-required
    #     register: reboot_required
    - name: Reboot
      ansible.builtin.reboot:
      # when: reboot_required.stat.exists
    # - name: Clear package cache (optional)
    #   ansible.builtin.file:
    #     path: /var/cache/pacman/pkg 
    #     state: absent

  post_tasks:
    - name: switch back to ro mode
      ansible.builtin.command: ro
